sudo: required
language: python
dist: xenial
python: 3.7

install:
  - pip install tox-travis
script:
  - tox -p 15 -- --cov=./
  - sonar-scanner -Dsonar.projectKey=symonk_pylenium  -Dsonar.organization=symonk-github
branches:
  only:
    - master
git:
  depth: 99999

before-install:
  - sleep 3
  - export CHROME_BIN=/usr/bin/google-chrome

services:
  xvfb

after_success:
  - codecov

cache:
  directories:
    - "$HOME/.sonar/cache"
addons:
  apt:
    update: true
  chrome: stable
  firefox: latest
  sonarcloud:
    organization: symonk-github

packages:
  - google-chrome-stable

notifications:
  email: false
