from typing import Callable

from pylenium.constants.strings import CHROME

BROWSER = CHROME
HEADLESS = False
SELENIUM_GRID_URL: str
BROWSER_RESOLUTION: str
BROWSER_VERSION: str
DRIVER_BINARY_PATH: str
browser_capabilities: dict
CHROME_OPTS: list
BASE_URL: str
EXPLICIT_WAIT: int
POLLING_INTERVAL: int
PAGE_SOURCE_ON_FAIL: bool
SCREENSHOT_ON_FAIL: bool
STACK_TRACE_ON_FAIL: bool
CLICK_WITH_JAVASCRIPT: bool
SENDKEYS_WITH_JAVASCRIPT: bool
DEFAULT_SELECTOR: str
DRIVER_LISTENER: Callable
BROWSER_NOT_MAXIMIZED: bool
